import type { ROICalculation } from './roi-calculator.js';

/**
 * Format ROI data as JSON
 */
export function formatAsJSON(calculations: ROICalculation[]): string {
  return JSON.stringify(calculations, null, 2);
}

/**
 * Format ROI data as Markdown report
 */
export function formatAsMarkdown(calculations: ROICalculation[], currency: string = 'USD'): string {
  if (calculations.length === 0) {
    return '# TONL ROI Analysis\n\nNo data to display.\n';
  }

  let markdown = '# 🚀 TONL ROI Analysis Report\n\n';
  
  if (calculations.length === 1) {
    // Single file detailed report
    const calc = calculations[0];
    markdown += `## 📊 Analysis Summary\n\n`;
    markdown += `- **File:** \`${calc.filename || 'data.json'}\`\n`;
    markdown += `- **Model:** ${calc.model.name} (${calc.model.provider})\n`;
    markdown += `- **Currency:** ${currency}\n`;
    markdown += `- **Analysis Date:** ${new Date().toISOString().split('T')[0]}\n\n`;
    
    markdown += `## 📈 Token Usage\n\n`;
    markdown += `| Format | Tokens | Percentage |\n`;
    markdown += `|--------|--------|------------|\n`;
    markdown += `| JSON   | ${calc.jsonTokens.toLocaleString()} | 100% |\n`;
    markdown += `| TONL   | ${calc.tonlTokens.toLocaleString()} | ${(100 - calc.savingsPercent).toFixed(1)}% |\n`;
    markdown += `| **Savings** | **${calc.savedTokens.toLocaleString()}** | **${calc.savingsPercent.toFixed(1)}%** |\n\n`;
    
    markdown += `## 💰 Cost Analysis\n\n`;
    markdown += `| Metric | JSON | TONL | Savings |\n`;
    markdown += `|--------|------|------|----------|\n`;
    markdown += `| Per 1K requests | $${(calc.costs.json.per1M / 1000).toFixed(2)} | $${(calc.costs.tonl.per1M / 1000).toFixed(2)} | $${(calc.costs.savings.per1M / 1000).toFixed(2)} |\n`;
    markdown += `| Per 1M requests | $${calc.costs.json.per1M.toFixed(2)} | $${calc.costs.tonl.per1M.toFixed(2)} | **$${calc.costs.savings.per1M.toFixed(2)}** |\n`;
    markdown += `| Per 10M requests | $${calc.costs.json.per10M.toFixed(2)} | $${calc.costs.tonl.per10M.toFixed(2)} | **$${calc.costs.savings.per10M.toLocaleString()}** |\n`;
    markdown += `| Per 100M requests | $${calc.costs.json.per100M.toLocaleString()} | $${calc.costs.tonl.per100M.toLocaleString()} | **$${calc.costs.savings.per100M.toLocaleString()}** |\n\n`;
    
    // Annual savings
    const annualSavings = (calc.costs.savings.per1M / 1000) * 365;
    markdown += `## 📅 Projected Annual Savings\n\n`;
    markdown += `At **1,000 requests per day**, you would save:\n\n`;
    markdown += `### 💎 $${annualSavings.toFixed(2)} per year\n\n`;
    
    // Recommendation
    markdown += `## ✅ Recommendation\n\n`;
    if (calc.savingsPercent >= 20) {
      markdown += `**STRONGLY USE TONL** - With ${calc.savingsPercent.toFixed(1)}% token savings, TONL provides significant cost reduction.\n\n`;
    } else if (calc.savingsPercent >= 10) {
      markdown += `**USE TONL** - With ${calc.savingsPercent.toFixed(1)}% token savings, TONL offers meaningful cost benefits.\n\n`;
    } else if (calc.savingsPercent > 0) {
      markdown += `**CONSIDER TONL** - With ${calc.savingsPercent.toFixed(1)}% token savings, TONL provides modest cost reduction.\n\n`;
    } else {
      markdown += `**LIMITED VALUE** - TONL provides minimal savings for this use case.\n\n`;
    }
    
  } else {
    // Multiple files summary
    markdown += `## 📊 Batch Analysis Summary\n\n`;
    markdown += `Analyzed **${calculations.length} files**\n\n`;
    
    // Calculate totals
    const totalJsonTokens = calculations.reduce((sum, c) => sum + c.jsonTokens, 0);
    const totalTonlTokens = calculations.reduce((sum, c) => sum + c.tonlTokens, 0);
    const avgSavings = calculations.reduce((sum, c) => sum + c.savingsPercent, 0) / calculations.length;
    const totalSavings = calculations.reduce((sum, c) => sum + c.costs.savings.per1M, 0);
    
    markdown += `### Overall Statistics\n\n`;
    markdown += `- **Total JSON Tokens:** ${totalJsonTokens.toLocaleString()}\n`;
    markdown += `- **Total TONL Tokens:** ${totalTonlTokens.toLocaleString()}\n`;
    markdown += `- **Average Savings:** ${avgSavings.toFixed(1)}%\n`;
    markdown += `- **Total Savings (per 1M requests):** $${totalSavings.toFixed(2)}\n\n`;
    
    // Per-file table
    markdown += `### Per-File Results\n\n`;
    markdown += `| File | Tokens (JSON) | Tokens (TONL) | Savings % | Cost Savings (per 1M) |\n`;
    markdown += `|------|---------------|---------------|-----------|----------------------|\n`;
    
    calculations.forEach(calc => {
      markdown += `| ${calc.filename || 'N/A'} | ${calc.jsonTokens.toLocaleString()} | ${calc.tonlTokens.toLocaleString()} | ${calc.savingsPercent.toFixed(1)}% | $${calc.costs.savings.per1M.toFixed(2)} |\n`;
    });
    
    markdown += `\n`;
  }
  
  markdown += `---\n\n`;
  markdown += `*Generated by TONL CLI v0.9.0 on ${new Date().toISOString()}*\n`;
  
  return markdown;
}
